version: '3.1'

services:
  mongo:
    image: mongo:6.0.13
    container_name: popularity-scorer-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: demo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d