spring:
  application.name: popularityScorer

  data.mongodb:
    host: localhost
    port: 27017
    database: demo
    username: demo_application
    password: demo_password
    auto-index-creation: true

GITHUB_BASE_URL: https://api.github.com